name: curriculo

services:
  Curriculo:
    image: curriculo:v1
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: Curriculo
    restart: unless-stopped
    ports:
      - "8100:8100"
      - "8086:8087"
    networks:
      - projetosdb-network
  nginx:
    image: nginx:alpine
    container_name: Curriculo-proxy
    restart: always
    ports:
      - "8088:80"
      - "2053:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ../cdn/ssl:/etc/nginx/ssl:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - Curriculo
    networks:
      - projetosdb-network

networks:
  projetosdb-network: 
    external: true
