worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # Aumenta o limite de upload para 10 Megabytes ---
    client_max_body_size 10M;

    # Configuração de Compressão (Gzip) para carregar o Angular mais rápido
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    server {
        listen 80;
        # Use seu dominio aqui
        server_name seudomínio.site;

        # Redireciona HTTP para HTTPS
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        # Use seu dominio aqui também
        server_name seudomínio.site;

        # Caminhos dos Certificados: conforme o volume no compose
        ssl_certificate     /etc/nginx/ssl/bycodeai.pem;
        ssl_certificate_key /etc/nginx/ssl/bycodeai.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Rota para o Frontend Ionic/Angular
        location / {
            proxy_pass http://Curriculo:8100;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Rota para a API .NET
        location {
            proxy_pass http://Curriculo:8087;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Timeout para requisições longas
            proxy_connect_timeout 90;
            proxy_send_timeout 90;
            proxy_read_timeout 90;
        }
    }
}